//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class dbOkulEntities : DbContext
    {
        public dbOkulEntities()
            : base("name=dbOkulEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tbl_Ogrenciler> Tbl_Ogrenciler { get; set; }
        public virtual DbSet<Tbl_Ogretmenler> Tbl_Ogretmenler { get; set; }
        public virtual DbSet<Tbl_Veliler> Tbl_Veliler { get; set; }
        public virtual DbSet<ilceler> ilceler { get; set; }
        public virtual DbSet<Tbl_Brans> Tbl_Brans { get; set; }
        public virtual DbSet<Tbl_Ayarlar> Tbl_Ayarlar { get; set; }
        public virtual DbSet<Tbl_OgrAyarlar> Tbl_OgrAyarlar { get; set; }
    
        public virtual ObjectResult<AyarlarOgrenciler_Result> AyarlarOgrenciler()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AyarlarOgrenciler_Result>("AyarlarOgrenciler");
        }
    
        public virtual ObjectResult<AyarlarOgretmenler_Result> AyarlarOgretmenler()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AyarlarOgretmenler_Result>("AyarlarOgretmenler");
        }
    }
}
