//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_OgrAyarlar
    {
        public int AyarlarOgrId { get; set; }
        public string OgrSifre { get; set; }
    
        public virtual Tbl_Ogrenciler Tbl_Ogrenciler { get; set; }
    }
}
