//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Ayarlar
    {
        public int AyarlarId { get; set; }
        public string OgrtSifre { get; set; }
    
        public virtual Tbl_Ogretmenler Tbl_Ogretmenler { get; set; }
        public virtual Tbl_Ogretmenler Tbl_Ogretmenler1 { get; set; }
    }
}
