//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Ogrenciler
    {
        public int OgrId { get; set; }
        public string OgrAd { get; set; }
        public string OgrSoyad { get; set; }
        public string OgrNo { get; set; }
        public string OgrSinif { get; set; }
        public string OgrDogTar { get; set; }
        public string OgrCinsiyet { get; set; }
        public string OgrTc { get; set; }
        public Nullable<int> OgrVeliId { get; set; }
        public string Ogrİl { get; set; }
        public string Ogrİlce { get; set; }
        public string OgrAdres { get; set; }
        public string OgrFoto { get; set; }
    
        public virtual Tbl_OgrAyarlar Tbl_OgrAyarlar { get; set; }
        public virtual Tbl_Veliler Tbl_Veliler { get; set; }
    }
}
